### ISSUE TITLE
Sample not found

### ISSUE THREAD

**Issue by alorma** [DavidPizarro/PinView#1]
The google play sample cannot be found

**Comment by DavidPizarro** [comment]
Indeed. The application is being uploaded to Google Play right now, it will
be a matter of hours.

When available, I will send you an email to more easily.

Thanks!

**Comment by DavidPizarro** [comment]
Hi again!

The sample application is now available on Google Play:

https://play.google.com/store/apps/details?id=com.dpizarro.libraries.pinview

Now, I'm uploading the library to Maven Nexus to make use of it with Gradle
or Maven.

Regards,

2015-08-28 9:27 GMT+02:00 David Pizarro dpizarro89@gmail.com:
