### ISSUE TITLE
Readme suggests incorrect gradle include

### ISSUE THREAD

**Issue by biddster** [DavidPizarro/PinView#2]
The readme suggests using the following:

```
compile 'com.github.dpizarro:pinview:LATEST'
```

However, that fails and after checking the repo, I think it should be this:

```
compile 'com.github.davidpizarro:pinview:1.0.0'
```

Thanks for a great library.

**Comment by DavidPizarro** [comment]
Hi!

Usually it indicates VERSION,  because version will increase, and it always appears on Github. Currently the version is 1.0.0.

So, now you have to replace VERSION by 1.0.0

**Comment by biddster** [comment]
Apologies, I should have been clearer. I had to replace `com.github.dpizarro` with `com.github.davidpizarro` in order to resolve the dependency.

**Comment by DavidPizarro** [comment]
Oh yes! You are right! I have modified Readme file. Thank you and sorry!

**Comment by biddster** [comment]
No problem, thanks again.
